version: '3'

services:
  openhackapi:
    image: openhack/minecraft-server:2.0-nanoserver
    ports:
      - "25565:25565"
    environment:
      - EULA=true
    reservations:
      memory: 2048M
networks:
  default:
    external:
      name: nat
